language: r
os: linux
warnings_are_errors: false
cache: packages
latex: false

r_packages:
    - plyr
    - usethis
    - roxygen2
    - remotes

apt_packages:
  - libudunits2-dev
  - libgdal-dev
  - libgeos-dev
  - libproj-dev
  - libv8-dev
  
script:
    - Rscript -e "remotes::install_github('cttedwards/redData', build_vignettes = TRUE, force = TRUE)"
    - R CMD build .

repos:
  CRAN: https://cran.rstudio.com
